server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transactiondb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: transaction-service
  config:
    import: configserver:http://localhost:9296

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
