server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/budgetdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: budget-service

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
